apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tw-automation-chart.fullname" . }}
  labels:
    {{- include "tw-automation-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tw-automation-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tw-automation-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tw-automation-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:          
          - name: "MYSQL_ROOT_PASSWORD"
            valueFrom:
              secretKeyRef:
                key:  MYSQL_ROOT_PASSWORD
                name: {{ .Release.Name }}-auth
          - name: "MYSQL_DATABASE"
            valueFrom:
              secretKeyRef:
                key:  MYSQL_DATABASE
                name: {{ .Release.Name }}-auth
          - name: "MYSQL_USER"
            valueFrom:
              secretKeyRef:
                key:  MYSQL_USER
                name: {{ .Release.Name }}-auth  
          - name: "MYSQL_PASSWORD"
            valueFrom:
              secretKeyRef:
                key:  MYSQL_PASSWORD
                name: {{ .Release.Name }}-auth          
          ports:
            - name: http
              containerPort: 3306
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
