apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.env.MYSQL_ROOT_PASSWORD | b64enc }}
  MYSQL_DATABASE: {{ .Values.env.MYSQL_DATABASE | b64enc }}
  MYSQL_USER: {{ .Values.env.MYSQL_USER | b64enc }}
  MYSQL_PASSWORD: {{ .Values.env.MYSQL_PASSWORD | b64enc }}