apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  MEDIAWIKI_DB_NAME: {{ .Values.env.MEDIAWIKI_DB_NAME | b64enc }}
  MEDIAWIKI_DB_HOST: {{ .Values.env.MEDIAWIKI_DB_HOST | b64enc }}
  MEDIAWIKI_DB_USER: {{ .Values.env.MEDIAWIKI_DB_USER | b64enc }}
  MEDIAWIKI_DB_PASSWORD: {{ .Values.env.MEDIAWIKI_DB_PASSWORD | b64enc }}