name: MediaWiki Build and Publish
on:
 push:
   branches: [ main ]
jobs:
 build-mariadb-image:
   name: 'Docker: Build and upload artifacts'
   runs-on: ubuntu-latest
   steps:
     -
       name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2
     -
       name: Login to DockerHub
       uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
     -
       name: Build and push
       uses: docker/build-push-action@v3
       with:
         file: ./Dockerfile.mariadb
         push: true
         tags: arjunm56i/mariadb-server-arjun:v1
 build-mediawiki-image:
   name: 'Docker: Build and upload artifacts'
   runs-on: ubuntu-latest
   steps:
     -
       name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2
     -
       name: Login to DockerHub
       uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
     -
       name: Build and push
       uses: docker/build-push-action@v3
       with:
         context: ./mediawiki
         file: ./mediawiki/Dockerfile
         push: true
         tags: arjunm56i/mediawiki-arjun:v1

 helm-lint:
   name: Helm lint and release
   runs-on: ubuntu-latest
   needs: build
   steps:
     - uses: actions/checkout@v2
     - name: Helm Lint
       uses: WyriHaximus/github-action-helm3@v2
       with:
         exec: helm lint ./tw-automation-chart
     - name: Helm install
       uses: WyriHaximus/github-action-helm3@v2
       with:
         exec: helm upgrade --install github-tw-automation ./tw-automation-chart
         kubeconfig: '${{ secrets.KUBECONFIG }}'
